#!/usr/bin/env bash

#SBATCH --job-name=coffee_exact
#SBATCH -p GPU
#SBATCH --gres gpu:1
#SBATCH --mem=64G 
#SBATCH -t 0 
#SBATCH -w compute-0-11
#SBATCH --output=coffee_exact.out

module load singularity
module load cuda-80
module load python36
module load python36-extras

BPY_IMG=/home/bokorn/containers/images/ubuntu-16.04-lts-GPU-bpy2.img 

srun singularity exec --nv $BPY_IMG ./ycb_002_master_chef_can_exact.sh

